routes/web.php
                Route::post('/profile/deposits/add_amount_handle', 'Profile\DepositsController@add_amount_handle')->name('profile.deposits.add_amount_handle');
                Route::get('/profile/deposits/finish', 'Profile\DepositsController@finish')->name('profile.deposits.finish');
                Route::post('/profile/deposits/finish_handle', 'Profile\DepositsController@finish_handle')->name('profile.deposits.finish_handle');
            });
            Route::get('/profile/deposits/add_fst/{id}', 'Profile\DepositsController@add_fst')->name('profile.deposits.add_fst');
            Route::get('/profile/deposits/change_days/{id}', 'Profile\DepositsController@change_days')->name('profile.deposits.change_days');
            Route::post('/profile/deposits/add_fst_handle', 'Profile\DepositsController@add_fst_handle')->name('profile.deposits.add_fst_handle');

        });
        Route::domain(env('SUBD'))->group(function () {
            Route::prefix('admin')->namespace('Admin')->group(function () {
                // Controllers Within The "App\Http\Controllers\Admin" Namespace
                Route::group(['middleware' => ['role:root|admin|writer']], function () {
                    Route::get('/', 'DashboardController@index')->name('admin');


                    Route::resource('/translations', 'TplTranslationsController', ['names' => [
                        'index' => 'admin.tpl_texts.index',
                        'index/{category?}' => 'admin.tpl_texts.index',
                        'create' => 'admin.tpl_texts.create',
                        'store' => 'admin.tpl_texts.store',
                        'edit' => 'admin.tpl_texts.edit',
                        'update' => 'admin.tpl_texts.update',
                        'destroy' => 'admin.tpl_texts.destroy',
                    ]]);


                    Route::resource('/news', 'NewsController', ['names' => [
                        'index' => 'admin.news.index',
                        'create' => 'admin.news.create',
                        'store' => 'admin.news.store',
                        'edit' => 'admin.news.edit',
                        'update' => 'admin.news.update',
                        'destroy' => 'admin.news.destroy',
                    ]]);

                    Route::resource('/reviews', 'ReviewsController', ['names' => [
                        'index' => 'admin.reviews.index',
                        'create' => 'admin.reviews.create',
                        'store' => 'admin.reviews.store',
                        'edit' => 'admin.reviews.edit',
                        'update' => 'admin.reviews.update',
                        'destroy' => 'admin.reviews.destroy',
                    ]]);
                    Route::resource('/faqs', 'FaqsController', ['names' => [
                        'index' => 'admin.faqs.index',
                        'create' => 'admin.faqs.create',
                        'store' => 'admin.faqs.store',
                        'edit' => 'admin.faqs.edit',
                        'update' => 'admin.faqs.update',
                        'destroy' => 'admin.faqs.destroy',
                    ]]);


                });


                Route::group(['middleware' => ['role:root|admin']], function () {

                    Route::prefix('/cashback')->as('admin.cashback.')->group(function() {
                        Route::get('dataTable', 'CashbackRequestController@dataTable')->name('dataTable');
                        Route::get('/export', 'CashbackRequestController@export')->name('export');
                        Route::resource('/', 'CashbackRequestController', ['parameters' => [
                            '' => 'cashback'
                        ]])->only(['index', 'show', 'update']);
                    });

                    Route::get('/impersonate/{id}', 'ImpersonateController@impersonate')->name('admin.impersonate');

                    Route::get('/deposits/block/{deposit}', 'DepositController@block')->name('admin.deposits.block');
                    Route::post('/deposits/change_rate/{deposit}', 'DepositController@changeRate')->name('admin.deposits.update_rate');
                    Route::post('/deposits/delete/{deposit}', 'DepositController@delete')->name('admin.deposits.delete');
                    Route::get('/deposits/unblock/{deposit}', 'DepositController@unblock')->name('admin.deposits.unblock');
                    Route::get('/deposits/dtdata', 'DepositController@dataTable')->name('admin.deposits.dtdata');
                    Route::resource('/deposits', 'DepositController', ['names' => [
                        'index' => 'admin.deposits.index',
                        'show' => 'admin.deposits.show',
                    ]]);
                    Route::post('/deposits', 'DepositController@filter')->name('admin.deposits.filter');


                    Route::get('/wallets/dtdata', 'WalletsController@dataTable')->name('admin.wallets.dtdata');
                    Route::get('/wallets/', 'WalletsController@index')->name('admin.wallets');


                    Route::get('/transactions/dtdata', 'TransactionsController@dataTable')->name('admin.transactions.dtdata');
                    Route::post('/transactions/approve-many', 'TransactionsController@approveMany')->name('admin.transactions.approve-many');

                    Route::get('/transactions/delete/{id}', 'TransactionsController@delete')->name('admin.transactions.delete');
                    Route::get('/transactions/approve/{id}', 'TransactionsController@approve')->name('admin.transactions.approve');
                    Route::resource('/transactions', 'TransactionsController', ['names' => [
                        'index' => 'admin.transactions.index',
                        'show' => 'admin.transactions.show',
                    ]]);

                    Route::resource('/langs', 'LanguagesController', ['names' => [
                        'index' => 'admin.langs.index',
                        'create' => 'admin.langs.create',
                        'store' => 'admin.langs.store',
                        'edit' => 'admin.langs.edit',
                        'update' => 'admin.langs.update',
                    ]]);
                    Route::get('/langs/destroy/{id}', 'LanguagesController@destroy')->name('admin.langs.destroy');

                    Route::get('/users/{user}/block', 'UsersController@block')->name('admin.users.block');
                    Route::get('/users/{user}/unblock', 'UsersController@unblock')->name('admin.users.unblock');

                    Route::get('/users/reftree/{id}', 'Technical\ReftreeController@show')->name('admin.users.reftree');
                    Route::get('/users/dtdata', 'UsersController@dataTable')->name('admin.users.dtdata');
                    Route::get('/users/dt-transactions/{user_id}', 'UsersController@dataTableTransactions')->name('admin.users.dt-transactions');
                    Route::get('/users/dt-deposits/{user_id}', 'UsersController@dataTableDeposits')->name('admin.users.dt-deposits');
                    Route::get('/users/dt-wrs/{user_id}', 'UsersController@dataTableWrs')->name('admin.users.dt-wrs');
                    Route::get('/users/dt-pvs/{user_id}', 'UsersController@dataTablePageViews')->name('admin.users.dt-pvs');
                    Route::get('/users/dt-trades/{user_id}', 'UsersController@dataTableTrades')->name('admin.users.dt-trades');
                    Route::get('/users/dt-orders/{user_id}', 'UsersController@dataTableOrders')->name('admin.users.dt-orders');
                    Route::resource('/users', 'UsersController', ['names' => [
                        'index' => 'admin.users.index',
                        'show' => 'admin.users.show',
                        'show/{level?}{plevel?}' => 'admin.users.show.level',
                        'edit' => 'admin.users.edit',
                        'update' => 'admin.users.update',
                        'destroy' => 'admin.users.destroy',
                    ]]);
                    Route::group(['middleware' => ['role:root']], function () {
                        Route::post('/users/bonus', 'UsersController@bonus')->name('admin.users.bonus');
                        Route::post('/users/penalty', 'UsersController@penalty')->name('admin.users.penalty');
                    });
                    Route::post('/users', 'UsersController@filter')->name('admin.users.filter');

                    Route::get('/users/reset2fa/{id}', 'UsersController@reset2fa')->name('admin.users.reset2fa');


                    Route::get('/export_ranks', 'UsersController@export_ranks')->name('admin.users.export_ranks');
                });

                Route::group(['middleware' => ['role:root']], function () {


                    Route::get('/statistic', 'StatisticController@index')->name('admin.statistic');

                    Route::get('/promo/usd', 'PromoController@usd')->name('admin.promo.usd');
                    Route::get('/promo/acc', 'PromoController@acc')->name('admin.promo.acc');

                    Route::get('/promo/ddata_usd', 'PromoController@ddata_usd')->name('admin.promo.ddata_usd');
                    Route::get('/promo/ddata_acc', 'PromoController@ddata_acc')->name('admin.promo.ddata_acc');


                    Route::get('/email_marketing', 'EmailMarketingController@index')->name('admin.email_marketing');
                    Route::post('/email_marketing', 'EmailMarketingController@handle')->name('admin.email_marketing.handle');

                    Route::get('/settings', 'SettingsController@index')->name('admin.settings.index');
                    Route::get('/settings/switch_site_status', 'SettingsController@switchSiteStatus')->name('admin.settings.switchSiteStatus');
                    Route::post('/settings/change-many', 'SettingsController@changeMany')->name('admin.settings.change-many');

app/Models/CashbackRequest.php
<?php

namespace App\Models;

use App\Traits\ModelTrait;
use App\Traits\Uuids;
use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

/**
 * Class CashbackRequest
 * @package App\Models
 * @property string $id
 * @property string $user_id
 * @property string $telegram
 * @property boolean $documents_checked
 * @property string $video_link
 * @property boolean $video_checked
 * @property string $comment
 * @property float $amount Cashback amount
 * @property string $result
 * @property boolean $approved
 */
class CashbackRequest extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;
    use Uuids;
    use ModelTrait;

    protected $keyType = 'string';
    public $incrementing = false;

    protected $fillable = [
        'user_id',
        'telegram',
        'documents_checked',
        'video_link',
        'video_checked',
        'comment',
        'amount',
        'result',
        'approved',
    ];

    public function documents()
    {
        return $this->morphMany(Media::class, 'model');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    /**
     * Approve cashback request
     * @param $amount
     * @param $result
     * @throws \Throwable
     */
    public function approve($amount, $result)
    {
        $currency = Currency::getByCode('FST');

        /** @var Wallet $wallet */
        $wallet = Wallet::query()
            ->where('user_id', $this->user_id)
            ->where('currency_id', $currency->id)
            ->lockForUpdate()
            ->first();

        \DB::transaction(function () use ($wallet, $amount, $result) {
            Transaction::cashback($wallet, $amount, $this->id);

            $wallet->addAmountWithoutAccrueToPartner($amount);

            $this->update([
                'amount' => $amount,
                'result' => $result,
                'video_checked' => true,
                'documents_checked' => true,
                'approved' => true
            ]);
        });
    }
}

app/Http/Controllers/Admin/CashbackRequestController.php
<?php


namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\RequestCashbackRequestUpdate;
use App\Models\CashbackRequest;
use Yajra\DataTables\DataTables;

class CashbackRequestController extends Controller
{
    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('admin.cashback_requests.index');
    }

    /**
     * @return mixed
     * @throws \Exception
     */
    public function dataTable()
    {
        $requests = CashbackRequest::query()
            ->with('user')
            ->get();

        return DataTables::of($requests)
            ->addIndexColumn()
            ->addColumn('show', function ($data) {
                return route('admin.cashback.show', ['cashback' => $data->id]);
            })
            ->addColumn('profile', function ($data) {
                return route('profile.cashback-result.show', ['id' => $data->id]);
            })
            ->addColumn('status', function($data) {
                return $data->approved === null
                    ? 'На рассмотрении'
                    : ($data->approved ? 'Одобрена' : 'Отклонена');
            })
            ->make(true);
    }

    /**
     * @param string $cashbackRequestId
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function show(string $cashbackRequestId)
    {
        /** @var CashbackRequest $cashbackRequest */
        $cashbackRequest = CashbackRequest::query()
            ->with(['user', 'documents'])
            ->find($cashbackRequestId);

        if (!$cashbackRequest) {
            return redirect(route('admin.cashback.index'))
                ->with('error', __('Request not found'));
        }

        return view('admin.cashback_requests.show', [
            'cashbackRequest' => $cashbackRequest,
            'user' => $cashbackRequest->user,
            'documents' => $cashbackRequest->getMedia('cashback_request')
        ]);
    }

    /**
     * Update cashback request
     * @param RequestCashbackRequestUpdate $request
     * @param $cashbackRequestId
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Throwable
     */
    public function update(RequestCashbackRequestUpdate $request, $cashbackRequestId)
    {
        /** @var CashbackRequest $cashbackRequest */
        $cashbackRequest = CashbackRequest::findOrFail($cashbackRequestId);

        $update = [];
        if ($request->filled('documents_checked')) {
            $update['documents_checked'] = $request->documents_checked == 1;
        }
        if ($request->filled('video_checked')) {
            $update['video_checked'] = $request->video_checked == 1;
        }
        if ($request->filled('approved')) {
            if ($request->approved) {
                try {
                    // Approve cashback request
                    $cashbackRequest->update([
                        'approved' => true,
                        'result' => $request->result
                    ]);
                    return back()->with('success', __('Cashback request approved'));
                } catch (\Exception $e) {
                    return back()->with('error', $e->getMessage())->withInput();
                }
            } else {
                // Reject cashback request
                $update += [
                    'approved' => false,
                    'result' => $request->result
                ];
            }
        }

        if (!empty($update)) {
            $cashbackRequest->update($update);
            return back()->with('success', __('Cashback request updated'));
        } else {
            return back()->with('error', __('Updated data request is empty'));
        }
    }
}

resources/views/admin/cashback_requests/index.blade.php
@extends('admin/layouts.app')
@section('title'){{ __('Cashback requests') }}@endsection
@section('breadcrumbs')
    <li> {{ __('Cashback requests') }}</li>
@endsection
@section('content')
    <!-- row -->
    <div class="row">
        <!-- col -->
        <div class="col-md-12">
            <!-- tile -->
            <section class="tile">

                <!-- tile header -->
                <div class="tile-header dvd dvd-btm">
                    <h1 class="custom-font">{{ __('Cashback requests') }}</h1>
                    <ul class="controls">
                        <li><a role="button" href="{{route('admin.cashback.export')}}">
                                <i class="fa fa-download"></i> {{ __('Export') }}
                            </a></li>
                        <li>
                            <a role="button" class="tile-fullscreen">
                                <i class="fa fa-expand"></i> {{ __('Fullscreen') }}
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- /tile header -->

                <!-- tile body -->
                <div class="tile-body">
                    <div class="table-responsive">
                        <table id="cashback-requests" class="js-datatables responsive nowrap no-sorting" data-page-length="25">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>{{ __('Created at') }}</th>
                                <th>{{ __('Login') }}</th>
                                <th>{{ __('Email') }}</th>
                                <th>{{ __('Telegram') }}</th>
                                <th>{{ __('Video link') }}</th>
                                <th>{{ __('Status') }}</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tfoot>
                            <style>
                                td.tdinput input {
                                    width: 100%;
                                }
                            </style>
                            <tr>
                                <th></th>
                                <th></th>
                                <td class="tdinput"></td>
                                <td class="tdinput"></td>
                                <td class="tdinput"></td>
                                <td></td>
                                <td class="tdinput"></td>
                                <td></td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                <!-- /tile body -->

            </section>
            <!-- /tile -->


        </div>
        <!-- /col -->
    </div>
    <!-- /row -->


@endsection

@push('load-scripts')
    <script>
        //initialize basic datatable
        var table = $('#cashback-requests').DataTable({
            "iDisplayLength": 25,
            "processing": true,
            "serverSide": true,
            "order": [[1, "desc"]],
            "ajax": '{{ route('admin.cashback.dataTable') }}',
            "columns": [
                {
                    "data": "DT_Row_Index", "orderable": false,"searchable": false , "render": function (data, type, row, meta) {
                        return meta.settings._iRecordsTotal-data+1;
                    }
                },
                {"data": "created_at"},
                {
                    "data": "user.login", "render": function (data, type, row) {
                        return '<a href="' + row['user_id'] + '" target="_blank">' + data + '</a>';
                    }
                },
                {
                    "data": "user.email", "render": function (data) {
                        return '<a href="mailto:' + data + '" target="_blank">' + data + '</a>';
                    }
                },
                {"data": "telegram"},
                {
                    "data": "video_link",
                    "render": function (data) {
                        return '<a href="' + data + '" target="_blank">' + data + '</a>';
                    }
                },
                {"data": "status"},
                {
                    "data": 'action',
                    "orderable": false,
                    "searchable": false,
                    "render": function (data, type, row, meta) {
                        return '<a href="' + row['show'] + '" target="_blank" class="btn btn-xs btn-default"><i class="glyphicon glyphicon-eye-open"></i> {{ __('show') }}</a>'
                            + '<a href="' + row['profile'] + '" target="_blank" class="btn btn-xs btn-default"><i class="glyphicon glyphicon-pencil"></i> {{ __('profile') }}</a>';
                    }
                }
            ],
            "aoColumnDefs": [
                {
                    'bSortable': false,
                    'aTargets': ["no-sort"],
                    'render': function (data, type, row) {
                        return data + ' (' + row[1] + ')';
                    },
                }],
            "aoColumnDefs": [
                {'bSortable': false, 'aTargets': ["no-sort"],}
            ],
            "dom": 'Rlfrtip',
            initComplete: function () {
                this.api().columns([2, 3, 4]).every(function () {
                    var column = this;
                    var input = document.createElement("input");
                    $(input).appendTo($(column.footer()).empty()).attr('placeholder', '{{ __('search ...') }}')
                        .on('change', function () {
                            column.search($(this).val(), false, false, true).draw();
                        });
                });
            }
        });

        //*initialize basic datatable
    </script>
@endpush

resources/views/admin/cashback_requests/show.blade.php
@extends('admin/layouts.app')
@section('title', __('Cashback request'))
@section('breadcrumbs')
    <li> {{ __('Cashback request') }}</li>
@endsection

@section('content')
    <!-- row -->
    <div class="row">
        <!-- col -->
        <div class="col-md-12">
            <!-- tile -->
            <section class="tile">

                <!-- tile header -->
                <div class="tile-header dvd dvd-btm">
                    <h1 class="custom-font">@yield('title')</h1>
                </div>
                <!-- /tile header -->

                <!-- tile body -->
                <div class="tile-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-lg-5">
                                    {{ __('Name:') }}
                                </div>
                                <div class="col-lg-7" style="font-weight:bold;">
                                    <a href="{{ route('admin.users.index', ['user' => $user->id]) }}">
                                        {{ $user->name }}
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-lg-5">
                                    {{ __('E-mail:') }}
                                </div>
                                <div class="col-lg-7" style="font-weight:bold;">
                                    <a href="mailto:{{ $user->email }}" target="_blank">{{ $user->email }}</a>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-lg-5">
                                    {{ __('Telegram:') }}
                                </div>
                                <div class="col-lg-7" style="font-weight:bold;">
                                    {{ $cashbackRequest->telegram }}
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-lg-5">
                                    {{ __('Documents:') }}
                                </div>
                                <div class="col-lg-7" style="font-weight:bold;">
                                    @foreach($documents as $document)
                                        <span>
                                            <a href="{{app('env') === 'develop' ? $document->getFullUrl() : $document->getUrl()}}" download>{{$document->name}}</a>
                                        </span>
                                    @endforeach
                                    @if(!$cashbackRequest->documents_checked)
                                    <form style="float:right;" action="{{route('admin.cashback.update', ['cashback' => $cashbackRequest->id])}}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <input type="text" hidden name="documents_checked" value="1">
                                        <button class="btn btn-xs btn-primary">Verify document</button>
                                    </form>
                                    @else
                                        <span class="green btn-success">(Verified)</span>
                                    @endif
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-lg-5">
                                    {{ __('Video link:') }}
                                </div>
                                <div class="col-lg-7" style="font-weight:bold;">
                                    <a href="{{$cashbackRequest->video_link}}" target="_blank">
                                        {{ $cashbackRequest->video_link }}
                                    </a>
                                    @if(!$cashbackRequest->video_checked)
                                    <form style="float:right;" action="{{route('admin.cashback.update', ['cashback' => $cashbackRequest->id])}}" method="POST">
                                        @csrf
                                        @method('PUT')
                                        <input type="text" hidden name="video_checked" value="1">
                                        <button class="btn btn-xs btn-primary">Verify video</button>
                                    </form>
                                    @else
                                        <span class="green btn-success">(Verified)</span>
                                    @endif
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-lg-5">
                                    {{ __('Comment:') }}
                                </div>
                                <div class="col-lg-7" style="font-weight:bold;">
                                    {{ $cashbackRequest->comment }}
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </section>
            <section class="tile">

                <!-- tile header -->
                <div class="tile-header dvd dvd-btm">
                    <h1 class="custom-font">Result</h1>
                </div>
                <!-- /tile header -->

                <!-- tile body -->
                <div class="tile-body">
                    @if($cashbackRequest->approved === null)
                    <form class="form-horizontal" method="POST" action="{{ route('admin.cashback.update', ['cashback' => $cashbackRequest->id]) }}">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="result" class="col-md-4 control-label">{{ __('Result') }}</label>
                            <div class="col-md-6">
                                <textarea class="form-control" name="result" required>{{ old('result', $cashbackRequest->result) }}</textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label" for="approved">Approved</label>
                            <div class="col-md-6">
                                <div>
                                    <input type="radio" name="approved" value="1" {{$cashbackRequest->result === true ? 'checked' : ''}}> Yes
                                </div>
                                <div>
                                    <input type="radio" name="approved" value="0" {{$cashbackRequest->result === false ? 'checked' : ''}}> No
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save result') }}
                                </button>
                            </div>
                        </div>
                    </form>
                    @else
                        <ul class="list-group">
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-lg-5">
                                        {{ __('Status') }}
                                    </div>
                                    <div class="col-lg-7" style="font-weight:bold;">
                                        {{$cashbackRequest->approved ? "Approved" : "Rejected"}}
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="row">
                                    <div class="col-lg-5">
                                        {{ __('Result') }}
                                    </div>
                                    <div class="col-lg-7" style="font-weight:bold;">
                                        {{$cashbackRequest->result}}
                                    </div>
                                </div>
                            </li>
                        </ul>
                    @endif
                </div>
            </section>
        </div>
    </div>
@endsection